package sourcing_test

import (
	"bytes"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"github.com/jazcarate/sp/internal/sourcing"
)

func TestMarkdown_NilState(t *testing.T) {
	var (
		s *sourcing.State
		b bytes.Buffer
	)

	err := s.Markdown(&b)

	assert.Empty(t, err)
	assert.Equal(t, "<!-- This file is generated by sp v1. Please don't edit it directly -->\n"+
		"# Split Chain\n\n"+
		"🗅 Starting out a new Split Chain and don't know \"what now?\". No problem! Check the [docs](https://github.com/jazcarate/sp/blob/master/docs/new_sp_now_what.md)\n"+
		"## Operations\n"+
		"Current trust configuration: **Trust** [(ℹ)]"+
		"(https://github.com/jazcarate/sp/blob/master/docs/understanding_a_report.md#trust)\n\n"+
		"### Log\n"+
		"🌈 Fresh new 🌈\n",
		b.String())
}

func TestMarkdown_EmptyState(t *testing.T) {
	var (
		s *sourcing.State = sourcing.NewState()
		b bytes.Buffer
	)

	err := s.Markdown(&b)

	assert.Empty(t, err)
	assert.Equal(t, "<!-- This file is generated by sp v1. Please don't edit it directly -->\n"+
		"# Split Chain\n\n"+
		"🗅 Starting out a new Split Chain and don't know \"what now?\". No problem! Check the [docs](https://github.com/jazcarate/sp/blob/master/docs/new_sp_now_what.md)\n"+
		"## Operations\n"+
		"Current trust configuration: **Trust** [(ℹ)]"+
		"(https://github.com/jazcarate/sp/blob/master/docs/understanding_a_report.md#trust)\n\n"+
		"### Log\n"+
		"🌈 Fresh new 🌈\n",
		b.String())
}

func TestMarkdown_OneParticipantState(t *testing.T) {
	var (
		s *sourcing.State
		b bytes.Buffer
	)

	s, _ = s.Apply(sourcing.AddParticipant{Name: "Joe", PublicKey: "1"}, time.Date(2020, time.April, 10, 14, 20, 10, 22, time.UTC))
	err := s.Markdown(&b)

	assert.Empty(t, err)
	assert.Equal(t, "<!-- This file is generated by sp v1. Please don't edit it directly -->\n"+
		"# Split Chain\n\n## At a glance [(ℹ)]((https://github.com/jazcarate/sp/blob/master/docs/understanding_a_report.md#at-a-glance))\n"+
		"| | [Joe](#joe) | \n"+
		"| --- |  ---: | \n"+
		"|[Joe](#joe)||\n\n"+
		"## Participants\n| Name | Split | %age |\n"+
		"| --- | ---: | ---: |\n"+
		"|[Joe](#joe)|0|0%|\n\n"+
		"## Details\n"+
		"### Joe\n"+
		"<!-- Public key 1 -->\n"+
		"You currently split the expenditures at **0%**.\n\n"+
		"## Operations\n"+
		"Current trust configuration: **Trust** [(ℹ)](https://github.com/jazcarate/sp/blob/master/docs/understanding_a_report.md#trust)\n\n"+
		"### Log [(go to the last ⬇)](#op-1)\n"+
		"| # |  Operation | On | Note | Status |\n"+
		"| ---: | --- | --- | --- | ---: |\n"+
		"|[1](#op-1)<a id=\"op-1\"></a>|➕ Add [Joe](#joe) <!-- Public key 1 --> <!-- Sign joaco 1 -->|2020-04-10T14:20:10Z||✅|\n",
		b.String())
}
